### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by davibe** [PatrickHeneise/oauth2api#1]
I am having a look at your code because i am in the process of implementing this and wanted to start from a good example. Here are some comments
- "/start" route should be seen as a 'consumer-side' route because its like you are on a website and click on 'facebook login' which makes you jump to the oauth provider server.
- Also the ExampleStrategy seems to me like something that is implemented on the consumer side. I think. Am I right ? maybe a clearer separation of consumer code and provider code would help
- I am having a hard time understanding where "authorization-code-*" is used (implicit authorization) and the scenario around it. I can only see where you put it in the database and nothing else.
- The oauth2 scenario works fine with a consumer. But let's say I have my own server with my own api, with my own apps connecting to it. I can use oauth2 to allow external services to access my users resources but how can I authorize my own users for using the http apis from my apps (mobile apps mostly) ? I can imagine I can make a custom shortcut but i suspect there is a more appropriate and recommended solution for it.

Thank you for your help

**Comment by PatrickHeneise** [comment]
as you can see, I haven't touched this code in 2 years. I remember everything worked with the example, but I can't tell you exactly how it worked, sorry.
